---
- name: Init Zabbix Agent
  hosts: slave2
  #define variable for zabbix
  vars:
     #zabbix master ip
     serverActiveIp: 172.16.251.26
     #service name of zabbix-agent
     zabbixAgentServiceName: zabbix-agent.service
     #refress time
     refreshActiveChecks: 60
     #path of zabbix configuration
     zabbixConfPath: /etc/zabbix
     #installation of zabbix
     zabbixInstallList:
                   - "zabbix-agent"
     #rpm key of zabbix
     zabbixKeyUrl: "http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX"
     #rpm of zabbix
     zabbixRpmUrl: "http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm"

     #install zabbix agent when install is true
     install: false
     #config the zabbix-agent configuration when config is true
     config: true
  vars_files:
    - vars/slave2.yml
  user: root
  roles:
   - initZabbixAgent
