---
- name: Install pip
  yum: name=python-pip state=present
     
- name: Install python expect
  pip:
    name: pexpect

- name: Open Firewall
  firewalld:
    port: '{{item}}/tcp'
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  with_items:
    - '{{service_ports}}'
  ignore_errors: true